"""create alerts model

Revision ID: 02659e110820
Revises: 64853553c980
Create Date: 2026-05-08 07:47:43.736546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02659e110820'
down_revision: Union[str, None] = '64853553c980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('histories_user_id_fkey', 'histories', type_='foreignkey')
    op.create_foreign_key(None, 'histories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'histories', type_='foreignkey')
    op.create_foreign_key('histories_user_id_fkey', 'histories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
