"""Add face_embedding to users

Revision ID: ca7b3bead3b3
Revises: 04c43f8fd85e
Create Date: 2026-05-13 09:59:23.558167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7b3bead3b3'
down_revision: Union[str, None] = '04c43f8fd85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('face_embedding', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'face_embedding')
    # ### end Alembic commands ###
